[2025-04-23T17:00:15.423+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:00:15.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:00:15.426+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:00:15.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:00:16.472+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:00:16.469+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:00:16.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:00:16.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.078 seconds
[2025-04-23T17:00:46.821+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:00:46.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:00:46.825+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:00:46.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:00:47.466+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:00:47.465+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:00:47.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:00:47.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.669 seconds
[2025-04-23T17:01:17.693+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:01:17.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:01:17.698+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:01:17.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:01:18.891+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:01:18.887+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:01:18.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:01:18.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.230 seconds
[2025-04-23T17:01:50.330+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:01:50.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:01:50.331+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:01:50.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:01:51.304+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:01:51.303+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:01:51.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:01:51.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.995 seconds
[2025-04-23T17:02:22.761+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:02:22.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:02:22.766+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:02:22.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:02:23.395+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:02:23.391+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:02:23.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:02:23.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.672 seconds
[2025-04-23T17:02:55.936+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:02:55.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:02:55.940+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:02:55.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:02:56.541+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:02:56.539+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:02:56.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:02:56.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.643 seconds
[2025-04-23T17:03:28.472+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:03:28.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:03:28.474+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:03:28.473+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:03:29.044+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:03:29.043+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:03:29.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:03:29.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.591 seconds
[2025-04-23T17:04:01.403+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:04:01.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:04:01.405+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:04:01.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:04:01.906+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:04:01.905+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:04:01.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:04:01.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.518 seconds
[2025-04-23T17:04:33.792+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:04:33.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:04:33.794+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:04:33.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:04:34.305+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:04:34.303+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:04:34.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:04:34.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.529 seconds
[2025-04-23T17:06:59.715+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:06:59.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:06:59.717+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:06:59.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:07:00.456+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:07:00.454+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:07:00.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:07:00.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.760 seconds
[2025-04-23T17:07:30.693+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:07:30.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:07:30.695+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:07:30.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:07:31.356+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:07:31.354+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:07:31.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:07:31.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.680 seconds
[2025-04-23T17:08:01.715+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:08:01.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:08:01.717+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:08:01.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:08:02.269+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:08:02.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:08:02.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:08:02.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.577 seconds
[2025-04-23T17:08:32.634+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:08:32.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:08:32.637+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:08:32.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:08:33.465+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:08:33.464+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:08:33.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:08:33.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.850 seconds
[2025-04-23T17:09:03.883+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:09:03.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:09:03.887+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:09:03.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:09:04.838+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:09:04.834+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:09:04.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:09:04.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.983 seconds
[2025-04-23T17:09:35.255+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:09:35.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:09:35.257+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:09:35.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:09:35.738+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:09:35.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:09:35.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:09:35.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.502 seconds
[2025-04-23T17:10:05.985+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:10:05.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:10:05.987+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:10:05.986+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:10:06.453+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:10:06.452+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:10:06.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:10:06.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.486 seconds
[2025-04-23T17:11:07.765+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:11:07.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:11:07.768+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:11:07.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:11:08.329+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:11:08.328+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:11:08.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:11:08.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.582 seconds
[2025-04-23T17:11:39.210+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:11:39.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:11:39.214+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:11:39.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:11:39.999+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:11:39.996+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:11:40.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:11:40.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.819 seconds
[2025-04-23T17:12:11.914+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:12:11.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:12:11.917+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:12:11.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:12:12.579+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:12:12.578+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:12:12.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:12:12.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.688 seconds
[2025-04-23T17:12:45.289+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:12:45.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:12:45.290+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:12:45.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:12:45.875+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:12:45.874+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:12:45.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:12:45.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.603 seconds
[2025-04-23T17:13:17.576+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:13:17.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:13:17.578+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:13:17.578+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:13:18.173+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:13:18.172+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:13:18.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:13:18.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.614 seconds
[2025-04-23T17:13:43.090+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:13:43.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:13:43.092+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:13:43.092+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:13:43.808+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:13:43.802+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:13:43.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:13:43.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.768 seconds
[2025-04-23T17:14:14.710+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:14:14.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:14:14.712+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:14:14.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:14:15.309+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:14:15.308+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:14:15.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:14:15.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.618 seconds
[2025-04-23T17:14:45.613+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:14:45.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:14:45.614+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:14:45.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:14:46.085+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:14:46.083+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:14:46.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:14:46.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.490 seconds
[2025-04-23T17:15:16.473+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:15:16.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:15:16.482+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:15:16.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:15:16.999+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:15:16.994+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:15:16.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:15:17.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.565 seconds
[2025-04-23T17:15:47.464+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:15:47.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:15:47.466+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:15:47.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:15:48.250+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:15:48.243+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:15:48.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:15:48.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.812 seconds
[2025-04-23T17:16:18.542+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:16:18.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:16:18.544+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:16:18.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:16:19.089+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:16:19.087+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 22, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:16:19.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:16:19.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.573 seconds
[2025-04-23T17:16:39.944+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:16:39.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:16:39.946+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:16:39.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:16:40.395+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:16:40.393+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:16:40.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:16:40.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.467 seconds
[2025-04-23T17:17:10.690+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:17:10.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:17:10.692+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:17:10.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:17:11.196+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:17:11.194+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:17:11.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:17:11.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.526 seconds
[2025-04-23T17:17:42.094+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:17:42.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:17:42.098+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:17:42.097+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:17:42.833+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:17:42.831+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:17:42.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:17:42.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.788 seconds
[2025-04-23T17:18:12.974+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:18:12.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:18:12.976+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:18:12.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:18:13.912+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:18:13.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:18:13.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:18:13.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.988 seconds
[2025-04-23T17:18:44.830+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:18:44.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:18:44.831+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:18:44.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:18:45.321+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:18:45.319+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:18:45.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:18:45.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.508 seconds
[2025-04-23T17:19:18.172+0000] {processor.py:161} INFO - Started process (PID=411) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:19:18.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:19:18.174+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:19:18.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:19:18.726+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:19:18.725+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:19:18.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:19:18.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.574 seconds
[2025-04-23T17:19:50.554+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:19:50.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:19:50.555+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:19:50.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:19:51.114+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:19:51.113+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:19:51.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:19:51.127+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.578 seconds
[2025-04-23T17:20:22.918+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:20:22.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:20:22.920+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:20:22.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:20:23.471+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:20:23.470+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:20:23.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:20:23.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.570 seconds
[2025-04-23T17:20:56.297+0000] {processor.py:161} INFO - Started process (PID=447) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:20:56.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:20:56.311+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:20:56.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:20:57.061+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:20:57.051+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:20:57.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:20:57.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.797 seconds
[2025-04-23T17:21:28.946+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:21:28.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:21:28.950+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:21:28.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:21:29.606+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:21:29.605+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:21:29.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:21:29.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.679 seconds
[2025-04-23T17:22:01.433+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:22:01.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:22:01.435+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:22:01.435+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:22:01.956+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:22:01.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 28, in <module>
    client = MongoClient(MONGODB_HOST)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 796, in __init__
    res = _validate_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser_shared.py", line 479, in _validate_uri
    raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2025-04-23T17:22:01.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:22:01.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.539 seconds
[2025-04-23T17:23:53.776+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:23:53.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:23:53.781+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:23:53.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:23:54.408+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:23:54.405+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:23:54.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:23:54.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.649 seconds
[2025-04-23T17:24:24.954+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:24:24.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:24:24.956+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:24:24.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:24:25.410+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:24:25.409+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:24:25.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:24:25.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.473 seconds
[2025-04-23T17:24:55.580+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:24:55.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:24:55.582+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:24:55.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:24:56.065+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:24:56.064+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:24:56.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:24:56.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.503 seconds
[2025-04-23T17:27:48.819+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:27:48.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:27:48.823+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:27:48.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:27:49.567+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:27:49.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:27:49.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:27:49.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.770 seconds
[2025-04-23T17:28:20.261+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:28:20.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:28:20.263+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:28:20.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:28:20.766+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:28:20.765+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:28:20.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:28:20.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.524 seconds
[2025-04-23T17:28:51.235+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:28:51.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:28:51.239+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:28:51.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:28:51.744+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:28:51.743+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:28:51.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:28:51.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.527 seconds
[2025-04-23T17:29:22.180+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:29:22.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:29:22.181+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:29:22.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:29:22.658+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:29:22.657+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:29:22.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:29:22.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.498 seconds
[2025-04-23T17:29:52.862+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:29:52.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:29:52.864+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:29:52.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:29:53.369+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:29:53.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 29, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:29:53.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:29:53.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.541 seconds
[2025-04-23T17:30:08.500+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:30:08.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:30:08.502+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:30:08.502+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:30:07.007+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:30:07.004+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 30, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:30:07.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:30:11.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.709 seconds
[2025-04-23T17:30:18.681+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:30:18.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:30:18.683+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:30:18.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:30:19.311+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:30:19.309+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 30, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 133, in __init__
    _check_name(name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/database_shared.py", line 27, in _check_name
    raise InvalidName("database name cannot be the empty string")
pymongo.errors.InvalidName: database name cannot be the empty string
[2025-04-23T17:30:19.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:30:19.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.653 seconds
[2025-04-23T17:33:43.916+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:33:43.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:33:43.919+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:33:43.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:33:44.710+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:33:44.708+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 30, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:33:44.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:33:44.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.810 seconds
[2025-04-23T17:34:15.425+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:34:15.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:34:15.427+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:34:15.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:34:15.918+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:34:15.917+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 30, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:34:15.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:34:15.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.513 seconds
[2025-04-23T17:34:46.351+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:34:46.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:34:46.354+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:34:46.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:34:46.850+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:34:46.849+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 30, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:34:46.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:34:46.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.529 seconds
[2025-04-23T17:35:17.228+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:35:17.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:35:17.231+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:35:17.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:35:17.828+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:35:17.827+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 30, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:35:17.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:35:17.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.622 seconds
[2025-04-23T17:35:48.024+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:35:48.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:35:48.025+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:35:48.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:35:48.628+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:35:48.625+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 30, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:35:48.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:35:48.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.626 seconds
[2025-04-23T17:36:06.089+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:36:06.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:36:06.091+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:36:06.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:36:06.612+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:36:06.611+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 31, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:36:06.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:36:06.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.542 seconds
[2025-04-23T17:36:36.942+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:36:36.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:36:36.944+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:36:36.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:36:37.588+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:36:37.587+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 31, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:36:37.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:36:37.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.685 seconds
[2025-04-23T17:37:08.371+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:37:08.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:37:08.374+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:37:08.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:37:08.910+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:37:08.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 31, in <module>
    db = client[MONGODB_DATABASE]
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1313, in __getitem__
    return database.Database(self, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 125, in __init__
    raise TypeError(f"name must be an instance of str, not {type(name)}")
TypeError: name must be an instance of str, not <class 'NoneType'>
[2025-04-23T17:37:08.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:37:08.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.573 seconds
[2025-04-23T17:38:57.881+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:38:57.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:38:57.882+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:38:57.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:38:58.513+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:38:58.543+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:38:58.543+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:38:58.557+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:38:58.557+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:38:58.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.696 seconds
[2025-04-23T17:39:29.221+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:39:29.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:39:29.223+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:39:29.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:39:29.694+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:39:29.773+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:39:29.772+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:39:29.783+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:39:29.783+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:39:29.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.583 seconds
[2025-04-23T17:40:01.685+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:40:01.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:40:01.687+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:40:01.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:40:02.347+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:40:02.369+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:40:02.368+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:40:02.379+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:40:02.378+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:40:02.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.715 seconds
[2025-04-23T17:40:34.147+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:40:34.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:40:34.149+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:40:34.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:40:34.620+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:40:34.640+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:40:34.640+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:40:34.648+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:40:34.648+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:40:34.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.516 seconds
[2025-04-23T17:41:07.482+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:41:07.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:41:07.501+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:41:07.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:41:08.013+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:41:08.034+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:41:08.034+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:41:08.043+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:41:08.043+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:41:08.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.579 seconds
[2025-04-23T17:41:39.731+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:41:39.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:41:39.733+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:41:39.732+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:41:40.354+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:41:40.376+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:41:40.375+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:41:40.386+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:41:40.385+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:41:40.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.673 seconds
[2025-04-23T17:42:12.271+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:42:12.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:42:12.292+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:42:12.289+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:42:12.861+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:42:12.882+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:42:12.882+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:42:12.892+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:42:12.892+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:42:12.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.649 seconds
[2025-04-23T17:42:45.003+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:42:45.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:42:45.004+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:42:45.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:42:45.610+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:42:45.634+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:42:45.634+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:42:45.648+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:42:45.648+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:42:45.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.670 seconds
[2025-04-23T17:43:17.816+0000] {processor.py:161} INFO - Started process (PID=470) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:43:17.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:43:17.830+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:43:17.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:43:18.315+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:43:18.336+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:43:18.336+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:43:18.348+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:43:18.348+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:43:18.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.551 seconds
[2025-04-23T17:43:50.803+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:43:50.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:43:50.809+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:43:50.808+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:43:51.424+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:43:51.447+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:43:51.446+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:43:51.457+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:43:51.457+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:43:51.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.692 seconds
[2025-04-23T17:44:23.319+0000] {processor.py:161} INFO - Started process (PID=544) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:44:23.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:44:23.321+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:44:23.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:44:23.828+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:44:23.849+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:44:23.849+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:44:23.859+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:44:23.859+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:44:23.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.558 seconds
[2025-04-23T17:44:56.155+0000] {processor.py:161} INFO - Started process (PID=571) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:44:56.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:44:56.157+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:44:56.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:44:56.824+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:44:56.851+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:44:56.850+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:44:56.866+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:44:56.865+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:44:56.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.748 seconds
[2025-04-23T17:45:28.754+0000] {processor.py:161} INFO - Started process (PID=630) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:45:28.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:45:28.782+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:45:28.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:45:29.250+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:45:29.270+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:45:29.269+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:45:29.278+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:45:29.278+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:45:29.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.540 seconds
[2025-04-23T17:46:01.167+0000] {processor.py:161} INFO - Started process (PID=645) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:46:01.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:46:01.169+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:46:01.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:46:01.604+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:46:01.624+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:46:01.624+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:46:01.633+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:46:01.633+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:46:01.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.484 seconds
[2025-04-23T17:46:33.945+0000] {processor.py:161} INFO - Started process (PID=660) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:46:33.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:46:33.946+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:46:33.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:46:34.387+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:46:34.408+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:46:34.407+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:46:34.417+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:46:34.417+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:46:34.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.489 seconds
[2025-04-23T17:47:06.752+0000] {processor.py:161} INFO - Started process (PID=675) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:47:06.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:47:06.754+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:47:06.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:47:07.207+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:47:07.226+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:47:07.225+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:47:07.236+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:47:07.236+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:47:07.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.501 seconds
[2025-04-23T17:47:39.595+0000] {processor.py:161} INFO - Started process (PID=690) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:47:39.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:47:39.597+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:47:39.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:47:40.158+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:47:40.183+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:47:40.183+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:47:40.193+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:47:40.193+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:47:40.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.617 seconds
[2025-04-23T17:48:12.235+0000] {processor.py:161} INFO - Started process (PID=705) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:48:12.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:48:12.238+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:48:12.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:48:12.899+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:48:12.928+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:48:12.927+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:48:12.938+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:48:12.938+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:48:12.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.722 seconds
[2025-04-23T17:48:44.830+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:48:44.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:48:44.831+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:48:44.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:48:45.579+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:48:45.610+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:48:45.609+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:48:45.627+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:48:45.626+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:48:45.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.824 seconds
[2025-04-23T17:49:17.658+0000] {processor.py:161} INFO - Started process (PID=735) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:49:17.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:49:17.660+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:49:17.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:49:18.185+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:49:18.210+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:49:18.209+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:49:18.218+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:49:18.218+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:49:18.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.577 seconds
[2025-04-23T17:49:43.365+0000] {processor.py:161} INFO - Started process (PID=750) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:49:43.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:49:43.368+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:49:43.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:49:43.945+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:49:43.969+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:49:43.968+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:49:43.980+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:49:43.980+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:49:44.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.646 seconds
[2025-04-23T17:50:14.611+0000] {processor.py:161} INFO - Started process (PID=765) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:50:14.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:50:14.613+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:50:14.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:50:15.263+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:50:15.291+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:50:15.290+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:50:15.301+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:50:15.301+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:50:15.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.707 seconds
[2025-04-23T17:50:45.715+0000] {processor.py:161} INFO - Started process (PID=780) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:50:45.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:50:45.716+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:50:45.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:50:46.465+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:50:46.537+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:50:46.535+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:50:46.551+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:50:46.550+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:50:46.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.861 seconds
[2025-04-23T17:51:16.996+0000] {processor.py:161} INFO - Started process (PID=794) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:51:16.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:51:16.999+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:51:16.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:51:17.866+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:51:17.962+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:51:17.960+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:51:17.972+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:51:17.972+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:51:17.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.997 seconds
[2025-04-23T17:51:48.871+0000] {processor.py:161} INFO - Started process (PID=809) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:51:48.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:51:48.873+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:51:48.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:51:49.739+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:51:49.871+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:51:49.867+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:51:49.881+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:51:49.881+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:51:49.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.041 seconds
[2025-04-23T17:52:20.653+0000] {processor.py:161} INFO - Started process (PID=824) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:52:20.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:52:20.655+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:52:20.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:52:21.439+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:52:21.545+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:52:21.542+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:52:21.557+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:52:21.557+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:52:21.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.926 seconds
[2025-04-23T17:52:52.586+0000] {processor.py:161} INFO - Started process (PID=839) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:52:52.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:52:52.588+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:52:52.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:52:53.446+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:52:53.507+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:52:53.504+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:52:53.517+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:52:53.516+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:52:53.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.951 seconds
[2025-04-23T17:53:24.210+0000] {processor.py:161} INFO - Started process (PID=854) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:53:24.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:53:24.212+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:53:24.212+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:53:24.929+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:53:24.982+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:53:24.981+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:53:24.992+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:53:24.992+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:53:25.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.803 seconds
[2025-04-23T17:53:55.594+0000] {processor.py:161} INFO - Started process (PID=869) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:53:55.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:53:55.794+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:53:55.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:54:36.351+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:54:32.159+0000] {timeout.py:68} ERROR - Process timed out, PID: 869
[2025-04-23T17:54:36.381+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:54:36.362+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prices_data_diff_method.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/prices_data_diff_method.py", line 3, in <module>
    import yfinance as yf
  File "/home/airflow/.local/lib/python3.10/site-packages/yfinance/__init__.py", line 23, in <module>
    from .search import Search
  File "/home/airflow/.local/lib/python3.10/site-packages/yfinance/search.py", line 24, in <module>
    from . import utils
  File "/home/airflow/.local/lib/python3.10/site-packages/yfinance/utils.py", line 36, in <module>
    import pandas as _pd
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "<frozen importlib._bootstrap>", line 1022, in _find_and_load
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/prices_data_diff_method.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.8.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.8.1/best-practices.html#reducing-dag-complexity, PID: 869
[2025-04-23T17:54:36.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:54:38.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 38.266 seconds
[2025-04-23T17:55:11.689+0000] {processor.py:161} INFO - Started process (PID=886) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:55:11.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:55:11.690+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:55:11.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:55:12.253+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:55:12.277+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:55:12.276+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:55:12.285+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:55:12.285+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:55:12.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.614 seconds
[2025-04-23T17:55:44.158+0000] {processor.py:161} INFO - Started process (PID=901) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:55:44.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:55:44.159+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:55:44.159+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:55:44.662+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:55:44.683+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:55:44.682+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:55:44.692+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:55:44.692+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:55:44.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.550 seconds
[2025-04-23T17:56:16.871+0000] {processor.py:161} INFO - Started process (PID=916) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:56:16.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:56:16.874+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:56:16.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:56:17.487+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:56:17.512+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:56:17.511+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:56:17.523+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:56:17.523+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:56:17.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.673 seconds
[2025-04-23T17:56:49.843+0000] {processor.py:161} INFO - Started process (PID=931) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:56:49.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:56:49.845+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:56:49.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:56:50.331+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:56:50.352+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:56:50.352+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:56:50.363+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:56:50.362+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:56:50.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.538 seconds
[2025-04-23T17:57:22.670+0000] {processor.py:161} INFO - Started process (PID=946) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:57:22.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:57:22.673+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:57:22.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:57:23.502+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:57:23.534+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:57:23.533+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:57:23.548+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:57:23.548+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:57:23.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.901 seconds
[2025-04-23T17:57:55.595+0000] {processor.py:161} INFO - Started process (PID=961) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:57:55.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:57:55.603+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:57:55.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:57:56.155+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:57:56.182+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:57:56.182+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:57:56.197+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:57:56.197+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:57:56.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.623 seconds
[2025-04-23T17:58:27.573+0000] {processor.py:161} INFO - Started process (PID=976) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:58:27.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:58:27.575+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:58:27.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:58:28.682+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:58:28.722+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:58:28.721+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:58:28.738+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:58:28.738+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:58:28.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.188 seconds
[2025-04-23T17:59:00.613+0000] {processor.py:161} INFO - Started process (PID=997) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:59:00.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:59:00.614+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:59:00.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:59:01.066+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:59:01.084+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:59:01.084+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:59:01.093+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:59:01.093+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:59:01.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.496 seconds
[2025-04-23T17:59:33.450+0000] {processor.py:161} INFO - Started process (PID=1012) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:59:33.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T17:59:33.452+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:59:33.452+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:59:33.939+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T17:59:33.960+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:59:33.960+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T17:59:33.969+0000] {logging_mixin.py:188} INFO - [2025-04-23T17:59:33.969+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T17:59:33.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.536 seconds
[2025-04-23T18:00:05.877+0000] {processor.py:161} INFO - Started process (PID=1031) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:00:05.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:00:05.885+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:00:05.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:00:07.683+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:00:07.711+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:00:07.711+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:00:07.723+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:00:07.723+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:00:07.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.867 seconds
[2025-04-23T18:00:38.585+0000] {processor.py:161} INFO - Started process (PID=1045) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:00:38.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:00:38.587+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:00:38.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:00:39.262+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:00:39.282+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:00:39.282+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:00:39.291+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:00:39.291+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:00:39.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.722 seconds
[2025-04-23T18:01:12.129+0000] {processor.py:161} INFO - Started process (PID=1060) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:01:12.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:01:12.131+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:01:12.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:01:12.717+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:01:12.736+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:01:12.736+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:01:12.744+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:01:12.744+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:01:12.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.633 seconds
[2025-04-23T18:01:44.023+0000] {processor.py:161} INFO - Started process (PID=1084) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:01:44.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:01:44.024+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:01:44.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:01:44.572+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:01:44.599+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:01:44.598+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:01:44.616+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:01:44.615+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:01:44.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.624 seconds
[2025-04-23T18:02:16.962+0000] {processor.py:161} INFO - Started process (PID=1105) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:02:16.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:02:16.964+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:02:16.964+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:02:17.442+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:02:17.463+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:02:17.462+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:02:17.472+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:02:17.472+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:02:17.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.527 seconds
[2025-04-23T18:02:49.795+0000] {processor.py:161} INFO - Started process (PID=1120) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:02:49.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:02:49.797+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:02:49.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:02:50.389+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:02:50.410+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:02:50.409+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:02:50.420+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:02:50.420+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:02:50.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.658 seconds
[2025-04-23T18:03:22.315+0000] {processor.py:161} INFO - Started process (PID=1135) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:03:22.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:03:22.318+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:03:22.317+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:03:22.984+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:03:23.045+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:03:23.044+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:03:23.071+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:03:23.070+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:03:23.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.788 seconds
[2025-04-23T18:03:54.979+0000] {processor.py:161} INFO - Started process (PID=1150) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:03:54.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:03:54.981+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:03:54.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:03:55.464+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:03:55.485+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:03:55.485+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:03:55.494+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:03:55.494+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:03:55.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.532 seconds
[2025-04-23T18:04:27.852+0000] {processor.py:161} INFO - Started process (PID=1165) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:04:27.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:04:27.854+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:04:27.854+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:04:28.441+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:04:28.463+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:04:28.463+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:04:28.475+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:04:28.475+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:04:28.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.642 seconds
[2025-04-23T18:05:00.840+0000] {processor.py:161} INFO - Started process (PID=1180) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:05:00.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:05:00.860+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:05:00.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:05:01.341+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:05:01.369+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:05:01.369+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:05:01.381+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:05:01.380+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:05:01.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.562 seconds
[2025-04-23T18:05:33.249+0000] {processor.py:161} INFO - Started process (PID=1207) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:05:33.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:05:33.251+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:05:33.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:05:33.797+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:05:33.818+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:05:33.817+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:05:33.827+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:05:33.827+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:05:33.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.597 seconds
[2025-04-23T18:06:06.133+0000] {processor.py:161} INFO - Started process (PID=1222) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:06:06.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:06:06.135+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:06:06.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:06:06.634+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:06:06.655+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:06:06.655+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:06:06.665+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:06:06.665+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:06:06.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 0.550 seconds
[2025-04-23T18:06:38.982+0000] {processor.py:161} INFO - Started process (PID=1243) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:06:38.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:06:38.984+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:06:38.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:06:40.491+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:06:40.539+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:06:40.538+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:06:40.551+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:06:40.551+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:06:40.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.588 seconds
[2025-04-23T18:07:11.946+0000] {processor.py:161} INFO - Started process (PID=1258) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:07:11.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:07:11.948+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:07:11.947+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:07:13.076+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:07:13.184+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:07:13.180+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:07:13.194+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:07:13.194+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:07:13.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.272 seconds
[2025-04-23T18:07:44.196+0000] {processor.py:161} INFO - Started process (PID=1272) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:07:44.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:07:44.198+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:07:44.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:07:45.137+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:07:45.364+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:07:45.354+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-04-23T18:07:45.401+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:07:45.395+0000] {dag.py:3823} INFO - Setting next_dagrun for prices_dag_taskflow to None, run_after=None
[2025-04-23T18:07:45.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prices_data_diff_method.py took 1.545 seconds
[2025-04-23T18:08:17.726+0000] {processor.py:161} INFO - Started process (PID=1286) to work on /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:08:17.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prices_data_diff_method.py for tasks to queue
[2025-04-23T18:08:17.729+0000] {logging_mixin.py:188} INFO - [2025-04-23T18:08:17.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:08:19.074+0000] {processor.py:840} INFO - DAG(s) 'prices_dag_taskflow' retrieved from /opt/airflow/dags/prices_data_diff_method.py
[2025-04-23T18:09:03.329+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
