[2025-04-24T21:06:03.773+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:06:01.596884+00:00 [queued]>
[2025-04-24T21:06:03.792+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:06:01.596884+00:00 [queued]>
[2025-04-24T21:06:03.793+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-24T21:06:03.812+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): branch_TCS.NS> on 2025-04-24 21:06:01.596884+00:00
[2025-04-24T21:06:03.831+0000] {standard_task_runner.py:60} INFO - Started process 3695 to run task
[2025-04-24T21:06:03.864+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'raw_prices_data_downloader_branching', 'branch_TCS.NS', 'manual__2025-04-24T21:06:01.596884+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/raw_price_data_testing.py', '--cfg-path', '/tmp/tmpk33q1hyb']
[2025-04-24T21:06:03.879+0000] {standard_task_runner.py:88} INFO - Job 211: Subtask branch_TCS.NS
[2025-04-24T21:06:04.118+0000] {task_command.py:423} INFO - Running <TaskInstance: raw_prices_data_downloader_branching.branch_TCS.NS manual__2025-04-24T21:06:01.596884+00:00 [running]> on host 8291240c5d79
[2025-04-24T21:06:04.292+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_prices_data_downloader_branching' AIRFLOW_CTX_TASK_ID='branch_TCS.NS' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T21:06:01.596884+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T21:06:01.596884+00:00'
[2025-04-24T21:06:04.296+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py:2709 UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://dochub.mongodb.org/core/pymongo-fork-deadlock
[2025-04-24T21:06:04.311+0000] {logging_mixin.py:188} INFO - ðŸ”„ No data found for TCS.NS, fetching new data...
[2025-04-24T21:06:04.311+0000] {python.py:201} INFO - Done. Returned value was: fetch_data_TCS.NS
[2025-04-24T21:06:04.312+0000] {branch.py:35} INFO - Branch into fetch_data_TCS.NS
[2025-04-24T21:06:04.312+0000] {skipmixin.py:178} INFO - Following branch fetch_data_TCS.NS
[2025-04-24T21:06:04.328+0000] {skipmixin.py:244} INFO - Skipping tasks [('skip_task_TCS.NS', -1)]
[2025-04-24T21:06:04.393+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=raw_prices_data_downloader_branching, task_id=branch_TCS.NS, execution_date=20250424T210601, start_date=20250424T210603, end_date=20250424T210604
[2025-04-24T21:06:04.433+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-24T21:06:04.464+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
