[2025-04-24T18:27:29.864+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_excel_from_mongo_dag_with_rsi.store_in_mysql_task manual__2025-04-24T18:27:23.542114+00:00 [queued]>
[2025-04-24T18:27:29.872+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_excel_from_mongo_dag_with_rsi.store_in_mysql_task manual__2025-04-24T18:27:23.542114+00:00 [queued]>
[2025-04-24T18:27:29.873+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-24T18:27:29.884+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): store_in_mysql_task> on 2025-04-24 18:27:23.542114+00:00
[2025-04-24T18:27:29.892+0000] {standard_task_runner.py:60} INFO - Started process 432 to run task
[2025-04-24T18:27:29.895+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'read_excel_from_mongo_dag_with_rsi', 'store_in_mysql_task', 'manual__2025-04-24T18:27:23.542114+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/indicator_dag.py', '--cfg-path', '/tmp/tmp9uw_awrm']
[2025-04-24T18:27:29.896+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask store_in_mysql_task
[2025-04-24T18:27:29.940+0000] {task_command.py:423} INFO - Running <TaskInstance: read_excel_from_mongo_dag_with_rsi.store_in_mysql_task manual__2025-04-24T18:27:23.542114+00:00 [running]> on host 8291240c5d79
[2025-04-24T18:27:30.028+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_excel_from_mongo_dag_with_rsi' AIRFLOW_CTX_TASK_ID='store_in_mysql_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T18:27:23.542114+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T18:27:23.542114+00:00'
[2025-04-24T18:27:30.109+0000] {logging_mixin.py:188} INFO - ✅ Database `intermediate` ensured to exist.
[2025-04-24T18:27:30.150+0000] {logging_mixin.py:188} INFO - ❌ MySQL Insert Error: (1050, "Table 'stock_data' already exists")
[2025-04-24T18:27:30.151+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-24T18:27:30.159+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=read_excel_from_mongo_dag_with_rsi, task_id=store_in_mysql_task, execution_date=20250424T182723, start_date=20250424T182729, end_date=20250424T182730
[2025-04-24T18:27:30.187+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-24T18:27:30.201+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
